# Generated by Django 4.1.2 on 2022-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[{'LIVRE', 'Livre'}, {'MANUTENÇÃO', 'Manutenção'}, {'Estragado', 'ESTRAGADO'}, {'Ocupado', 'OCUPADO'}], default='LIVRE', max_length=10)),
            ],
        ),
    ]
