# Generated by Django 4.1.2 on 2022-11-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Local', '0001_initial'),
        ('Status', '0001_initial'),
        ('Categoria', '0001_initial'),
        ('Fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Categoria.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Fornecedor.fornecedor')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Local.local')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Status.status')),
            ],
        ),
    ]
